site_name: Yahya's Oracle
site_description: My personal digital garden
site_author: Yahyaqr
site_url: https://yahyaqr.github.io/oracle
theme:
    name: 'material'
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.top
        - navigation.path
        - toc.follow
    icon:
        admonition:
          note: octicons/tag-16
          abstract: octicons/checklist-16
          info: octicons/info-16
          tip: octicons/squirrel-16
          success: octicons/check-16
          question: octicons/question-16
          warning: octicons/alert-16
          failure: octicons/x-circle-16
          danger: octicons/zap-16
          bug: octicons/bug-16
          example: octicons/beaker-16
          quote: octicons/quote-16
    palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  # The Footnotes extension allows to define inline footnotes, which are then rendered below all Markdown content of a document.
  - footnotes
  # The Attribute Lists extension allows to add HTML attributes and CSS classes
  - attr_list
  # The Markdown in HTML extension allows for writing Markdown inside of HTML
  - md_in_html
  # The Admonition extension adds support for admonitions, more commonly known as call-outs, which can be defined in Markdown by using a simple syntax.
  - admonition
  # The Details extension supercharges the Admonition extension, making the resulting call-outs collapsible, allowing them to be opened and closed by the user.
  - pymdownx.details
  # The SuperFences extension allows for arbitrary nesting of code and content blocks inside each other, including admonitions, tabs, lists and all other elements.
  - pymdownx.superfences
  # The Tabbed extension allows the usage of content tabs, a simple way to group related content and code blocks under accessible tabs.
  - pymdownx.tabbed:
      alternate_style: true
  # The Tasklist extension allows for the usage of GitHub Flavored Markdown inspired task lists
  - pymdownx.tasklist:
      custom_checkbox: true
  # The Definition Lists extension adds the ability to add definition lists.
  - def_list
  # Integrates with Mermaid.js, a very popular and flexible solution for drawing diagrams.
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # Provides support for several HTML elements that can be used to highlight or apply specific formatting.
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  # The Table of Contents extension automatically generates a table of contents from a document.
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks

extra:
  generator: false
  social:
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/yahyaqr/
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/yahya-aqrom/
    - icon: fontawesome/brands/github 
      link: https://github.com/yahyaqr/oracle
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
